// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeR4lOMn_l9Q0No2cGayiMiDJtT8Beir4',
    appId: '1:552901894251:web:e26bd7b8f3bcec0e8e512e',
    messagingSenderId: '552901894251',
    projectId: 'firstproject-55a09',
    authDomain: 'firstproject-55a09.firebaseapp.com',
    storageBucket: 'firstproject-55a09.appspot.com',
    measurementId: 'G-RZ5KS3ZMXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBMNuWOtRuqP1H9l3LbD3GPz4Ddio3F9M',
    appId: '1:552901894251:android:66f1a0b592a916bf8e512e',
    messagingSenderId: '552901894251',
    projectId: 'firstproject-55a09',
    storageBucket: 'firstproject-55a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQTEur-wEsct02nReXBuaV3SlnyZsIwKc',
    appId: '1:552901894251:ios:c557c496d9069ca58e512e',
    messagingSenderId: '552901894251',
    projectId: 'firstproject-55a09',
    storageBucket: 'firstproject-55a09.appspot.com',
    iosBundleId: 'com.example.firstFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQTEur-wEsct02nReXBuaV3SlnyZsIwKc',
    appId: '1:552901894251:ios:c557c496d9069ca58e512e',
    messagingSenderId: '552901894251',
    projectId: 'firstproject-55a09',
    storageBucket: 'firstproject-55a09.appspot.com',
    iosBundleId: 'com.example.firstFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeR4lOMn_l9Q0No2cGayiMiDJtT8Beir4',
    appId: '1:552901894251:web:5b86f35a723e22328e512e',
    messagingSenderId: '552901894251',
    projectId: 'firstproject-55a09',
    authDomain: 'firstproject-55a09.firebaseapp.com',
    storageBucket: 'firstproject-55a09.appspot.com',
    measurementId: 'G-NDSN19K7D7',
  );
}
